<a href="https://colab.research.google.com/github/MajdTaweel/cv-project-2/blob/main/plate_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install imageai==2.1.5 tensorflow==1.14.0 tensorflow-gpu==1.14.0 keras==2.3.1

     |████████████████████████████████| 184kB 6.0MB/s 
     |████████████████████████████████| 109.2MB 38kB/s 
     |████████████████████████████████| 377.0MB 48kB/s 
     |████████████████████████████████| 378kB 52.0MB/s 
     |████████████████████████████████| 51kB 8.3MB/s 
     |████████████████████████████████| 491kB 54.9MB/s 
     |████████████████████████████████| 3.2MB 53.9MB/s 
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorboard 2.4.0
    Uninstalling tensorboard-2.4.0:
      Successfully uninstalled tensorboard-2.4.0
  Found existing installation: tensorflow 2.4.0
    Uninstalling tensorflow-2.4.0:
      Successfully uninstalled tensorflow-2.4.0
  Found existing installation: Keras 2.4.3
    Uninstalling Keras-2.4.3:
      Successfully uninstalled Keras-2.4.3


In [ ]:
#!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/essential-v4/pretrained-yolov3.h5

--2021-01-15 02:46:52--  https://github.com/OlafenwaMoses/ImageAI/releases/download/essential-v4/pretrained-yolov3.h5
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-production-release-asset-2e65be.s3.amazonaws.com/125932201/12701d80-b2ab-11e9-9f56-c06e1dfbec05?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210115T024652Z&X-Amz-Expires=300&X-Amz-Signature=952e5d9cc673c5205d5bcc2b5a2c03d9b1865b2d87cb22cad0c1537eab746d90&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=125932201&response-content-disposition=attachment%3B%20filename%3Dpretrained-yolov3.h5&response-content-type=application%2Foctet-stream [following]
--2021-01-15 02:46:52--  https://github-production-release-asset-2e65be.s3.amazonaws.com/125932201/12701d80-b2ab-11e9-9f56-c06e1dfbec05?X-Amz-Algorit

**get a custom trained model**

In [8]:
from google.colab import drive, files
drive.mount('/content/drive')
!cp -r "/content/drive/My Drive/PalestinePlateModels2/detection_model-ex-005--loss-0003.806.h5" /content
drive.flush_and_unmount()

Mounted at /content/drive


In [2]:
from google.colab import drive, files
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!rm -r /content/plates
!cp -r "/content/drive/My Drive/PalestinePlateDataSet" /content
!mv /content/PalestinePlateDataSet /content/plates

rm: cannot remove '/content/plates': No such file or directory


In [4]:
drive.flush_and_unmount()

In [5]:
!mv /content/plates/annotations /content/plates/txt-annotations
!mkdir /content/plates/annotations
!mkdir /content/plates/train
!mkdir /content/plates/train/images
!mkdir /content/plates/train/annotations
!mkdir /content/plates/validation
!mkdir /content/plates/validation/images
!mkdir /content/plates/validation/annotations

In [6]:
!rm /content/plates/{train,validation}/*/*

rm: cannot remove '/content/plates/train/*/*': No such file or directory
rm: cannot remove '/content/plates/validation/*/*': No such file or directory


In [7]:
import os, random

directory = '/content/plates';

filenames = os.listdir(directory + '/txt-annotations')

indices=[i for i in range(len(filenames))]

random.seed(2021)
random.shuffle(indices)

split = int(0.8 * len(filenames))
filesplits = {
    'train': [filenames[idx] for idx in indices[:split]],
    'validation': [filenames[idx] for idx in indices[split:]]
}

In [9]:
from PIL import Image 
from lxml.etree import Element, SubElement, tostring
import pprint
from xml.dom.minidom import parseString

i = 0

for key in filesplits:
  for filename in filesplits[key]:
    
    ########
    print(i)
    i += 1
    ########
    # if i == 5:
    #   i = 0
    #   break
    
    if filename.endswith(".txt"): 
      with open(os.path.join(directory, 'txt-annotations', filename), 'r') as f:
        lines = f.readlines()
        plate = lines[0].strip()
        box = lines[1].strip().split(' ')
        imgname = filename.split('.')[0] + '.jpg'
        xmlname = filename.split('.')[0] + '.xml'
        img = Image.open(os.path.join(directory, 'images', imgname))
        resizedimg = img.resize((128, 128))
        resizedimg.save(os.path.join(directory, key, 'images', imgname))
        
        node_root = Element('annotation')
        
        node_folder = SubElement(node_root, 'folder')
        node_folder.text = key
        
        node_filename = SubElement(node_root, 'filename')
        node_filename.text = imgname
        
        node_size = SubElement(node_root, 'size')
        node_width = SubElement(node_size, 'width')
        node_width.text = str(resizedimg.width)
        
        node_height = SubElement(node_size, 'height')
        node_height.text = str(resizedimg.height)
        
        node_depth = SubElement(node_size, 'depth')
        node_depth.text = '3'
        
        node_object = SubElement(node_root, 'object')
        node_name = SubElement(node_object, 'name')
        node_name.text = 'plate'
        node_difficult = SubElement(node_object, 'difficult')
        node_difficult.text = '0'
        node_bndbox = SubElement(node_object, 'bndbox')
        node_xmin = SubElement(node_bndbox, 'xmin')
        node_xmin.text = str(round((int(box[0]) / img.width) * resizedimg.width))
        node_ymin = SubElement(node_bndbox, 'ymin')
        node_ymin.text = str(round((int(box[1]) / img.height) * resizedimg.height))
        node_xmax = SubElement(node_bndbox, 'xmax')
        node_xmax.text = str(round((int(box[2]) / img.width) * resizedimg.width))
        node_ymax = SubElement(node_bndbox, 'ymax')
        node_ymax.text = str(round((int(box[3]) / img.height) * resizedimg.height))
        
        xml = tostring(node_root, pretty_print=True) #Formatted display, the newline of the newline
        dom = parseString(xml)
        print(xml)
        with open(os.path.join(directory, key, 'annotations', xmlname), 'wb') as xmlfile:
          xmlfile.write(xml)

0
b'<annotation>\n  <folder>train</folder>\n  <filename>img01166.jpg</filename>\n  <size>\n    <width>128</width>\n    <height>128</height>\n    <depth>3</depth>\n  </size>\n  <object>\n    <name>plate</name>\n    <difficult>0</difficult>\n    <bndbox>\n      <xmin>66</xmin>\n      <ymin>97</ymin>\n      <xmax>99</xmax>\n      <ymax>111</ymax>\n    </bndbox>\n  </object>\n</annotation>\n'
1
b'<annotation>\n  <folder>train</folder>\n  <filename>img01384.jpg</filename>\n  <size>\n    <width>128</width>\n    <height>128</height>\n    <depth>3</depth>\n  </size>\n  <object>\n    <name>plate</name>\n    <difficult>0</difficult>\n    <bndbox>\n      <xmin>43</xmin>\n      <ymin>105</ymin>\n      <xmax>77</xmax>\n      <ymax>113</ymax>\n    </bndbox>\n  </object>\n</annotation>\n'
2
b'<annotation>\n  <folder>train</folder>\n  <filename>img00343.jpg</filename>\n  <size>\n    <width>128</width>\n    <height>128</height>\n    <depth>3</depth>\n  </size>\n  <object>\n    <name>plate</name>\n    <

In [10]:
!rm /content/plates/models/*

rm: cannot remove '/content/plates/models/*': No such file or directory


In [12]:
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="plates")
trainer.setTrainConfig(object_names_array=["plate"], batch_size=4, num_experiments=5, train_from_pretrained_model="detection_model-ex-005--loss-0003.806.h5")
trainer.trainModel()

Generating anchor boxes for training images and annotation...


/usr/local/lib/python3.6/dist-packages/imageai/Detection/Custom/gen_anchors.py:15: RuntimeWarning: invalid value encountered in double_scalars
  similarity = w*h/(c_w*c_h)


Average IOU for 9 anchors: nan
Anchor Boxes generated.
Detection configuration saved in  plates/json/detection_config.json
Training on: 	['plate']
Training with Batch Size:  4
Number of Experiments:  5
Training with transfer learning from pretrained Model


/usr/local/lib/python3.6/dist-packages/keras/callbacks/callbacks.py:998: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '


Epoch 1/5
2976/2976 [==============================] - 2072s 696ms/step - loss: 4.0924 - yolo_layer_4_loss: 0.7764 - yolo_layer_5_loss: 1.0299 - yolo_layer_6_loss: 2.2862 - val_loss: 6.9226 - val_yolo_layer_4_loss: 1.1580 - val_yolo_layer_5_loss: 1.4978 - val_yolo_layer_6_loss: 1.8676

Epoch 2/5
2976/2976 [==============================] - 2010s 676ms/step - loss: 3.4534 - yolo_layer_4_loss: 0.7472 - yolo_layer_5_loss: 0.8845 - yolo_layer_6_loss: 1.8217 - val_loss: 2.2901 - val_yolo_layer_4_loss: 0.9019 - val_yolo_layer_5_loss: 1.5500 - val_yolo_layer_6_loss: 1.8381
Epoch 3/5
2976/2976 [==============================] - 2020s 679ms/step - loss: 3.4641 - yolo_layer_4_loss: 0.7671 - yolo_layer_5_loss: 0.9285 - yolo_layer_6_loss: 1.7685 - val_loss: 4.6496 - val_yolo_layer_4_loss: 1.0832 - val_yolo_layer_5_loss: 1.4685 - val_yolo_layer_6_loss: 1.8240
Epoch 4/5
2976/2976 [==============================] - 2017s 678ms/step - loss: 3.3891 - yolo_layer_4_loss: 0.6959 - yolo_layer_5_loss: 0.923

In [13]:
from google.colab import drive, files
drive.mount('/content/drive')
!cp -r /content/plates/models "/content/drive/My Drive/PalestinePlateModels3"
!cp -r /content/plates/json "/content/drive/My Drive/PalestinePlateModels3/json"
drive.flush_and_unmount()

Mounted at /content/drive


In [ ]:
# from PIL import Image 
# import os

# dataset = []
# directory = '/content/drive/My Drive/PalestinePlateDataSet';
# i = 0

# for filename in os.listdir(directory + '/annotation'):
#   print(filename, i)
#   i += 1
#   if filename.endswith(".txt"): 
#     obj = {}
#     with open(os.path.join(directory, 'annotation', filename), 'r') as f:
#       lines = f.readlines()
#       obj['plate'] = lines[0].strip()
#       obj['box'] = lines[1].strip().split(' ')
#     imgname = filename.split('.')[0] + '.jpg'
#     obj['img'] = Image.open(os.path.join(directory, 'images', imgname))
#     dataset.append(obj)

In [ ]:
###########

In [ ]:
# # keras imports for the dataset and building our neural network
# from keras.datasets import mnist
# from keras.models import Sequential
# from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
# from keras.utils import np_utils

# # to calculate accuracy
# from sklearn.metrics import accuracy_score

# # loading the dataset
# (X_train, y_train), (X_test, y_test) = mnist.load_data()
# print(X_train)
# print(X_train.shape)
# print(y_train)
# print(y_train.shape)

# # building the input vector from the 28x28 pixels
# X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
# X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
# X_train = X_train.astype('float32')
# X_test = X_test.astype('float32')

# # normalizing the data to help with the training
# X_train /= 255
# X_test /= 255

# # one-hot encoding using keras' numpy-related utilities
# n_classes = 10
# print("Shape before one-hot encoding: ", y_train.shape)
# Y_train = np_utils.to_categorical(y_train, n_classes)
# Y_test = np_utils.to_categorical(y_test, n_classes)
# print("Shape after one-hot encoding: ", Y_train.shape)

# # building a linear stack of layers with the sequential model
# model = Sequential()
# # convolutional layer
# model.add(Conv2D(25, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape=(28,28,1)))
# model.add(MaxPool2D(pool_size=(1,1)))
# # flatten output of conv
# model.add(Flatten())
# # hidden layer
# model.add(Dense(100, activation='relu'))
# # output layer
# model.add(Dense(10, activation='softmax'))

# # compiling the sequential model
# model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# # training the model for 10 epochs
# model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data=(X_test, Y_test))

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
(60000, 28, 28)
[5 0 4 ... 5 6 8]
(60000,)
Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)
Epoch 1/10
208/469 [============>.................] - ETA: 17s - loss: 0.5460 - accuracy: 0.8410

KeyboardInterrupt: ignored