<a href="https://colab.research.google.com/github/MajdTaweel/cv-project-2/blob/main/plate_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install imageai==2.1.5 tensorflow==1.14.0 tensorflow-gpu==1.14.0 keras==2.3.1

     |████████████████████████████████| 184kB 6.5MB/s 
     |████████████████████████████████| 109.2MB 96kB/s 
     |████████████████████████████████| 377.0MB 43kB/s 
     |████████████████████████████████| 378kB 42.1MB/s 
     |████████████████████████████████| 51kB 6.2MB/s 
     |████████████████████████████████| 3.2MB 39.4MB/s 
     |████████████████████████████████| 491kB 45.6MB/s 
  Found existing installation: tensorboard 2.4.0
    Uninstalling tensorboard-2.4.0:
      Successfully uninstalled tensorboard-2.4.0
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorflow 2.4.0
    Uninstalling tensorflow-2.4.0:
      Successfully uninstalled tensorflow-2.4.0
  Found existing installation: Keras 2.4.3
    Uninstalling Keras-2.4.3:
      Successfully uninstalled Keras-2.4.3


In [1]:
!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/essential-v4/pretrained-yolov3.h5

--2021-01-15 02:46:52--  https://github.com/OlafenwaMoses/ImageAI/releases/download/essential-v4/pretrained-yolov3.h5
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-production-release-asset-2e65be.s3.amazonaws.com/125932201/12701d80-b2ab-11e9-9f56-c06e1dfbec05?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210115T024652Z&X-Amz-Expires=300&X-Amz-Signature=952e5d9cc673c5205d5bcc2b5a2c03d9b1865b2d87cb22cad0c1537eab746d90&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=125932201&response-content-disposition=attachment%3B%20filename%3Dpretrained-yolov3.h5&response-content-type=application%2Foctet-stream [following]
--2021-01-15 02:46:52--  https://github-production-release-asset-2e65be.s3.amazonaws.com/125932201/12701d80-b2ab-11e9-9f56-c06e1dfbec05?X-Amz-Algorit

In [2]:
from google.colab import drive, files
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
!rm -r /content/plates
!cp -r "/content/drive/My Drive/PalestinePlateDataSet" /content
!mv /content/PalestinePlateDataSet /content/plates
!mv /content/plates/annotations /content/plates/txt-annotations
!mkdir /content/plates/annotations
!mkdir /content/plates/train
!mkdir /content/plates/train/images
!mkdir /content/plates/train/annotations
!mkdir /content/plates/validation
!mkdir /content/plates/validation/images
!mkdir /content/plates/validation/annotations

rm: cannot remove '/content/plates': No such file or directory
mkdir: cannot create directory ‘/content/plates/train’: File exists
mkdir: cannot create directory ‘/content/plates/train/images’: File exists
mkdir: cannot create directory ‘/content/plates/train/annotations’: File exists
mkdir: cannot create directory ‘/content/plates/validation’: File exists
mkdir: cannot create directory ‘/content/plates/validation/images’: File exists
mkdir: cannot create directory ‘/content/plates/validation/annotations’: File exists


In [ ]:
# drive.flush_and_unmount()

In [6]:
import os, random

directory = '/content/plates';

filenames = os.listdir(directory + '/txt-annotations')

indices=[i for i in range(len(filenames))]

random.seed(2021)
random.shuffle(indices)

split = int(0.8 * len(filenames))
filesplits = {
    'train': [filenames[idx] for idx in indices[:split]],
    'validation': [filenames[idx] for idx in indices[split:]]
}

In [7]:
from PIL import Image 
from lxml.etree import Element, SubElement, tostring
import pprint
from xml.dom.minidom import parseString

i = 0

for key in filesplits:
  for filename in filesplits[key]:
    
    ########
    print(i)
    i += 1
    ########
    if i == 5:
      i = 0
      break
    
    if filename.endswith(".txt"): 
      with open(os.path.join(directory, 'txt-annotations', filename), 'r') as f:
        lines = f.readlines()
        plate = lines[0].strip()
        box = lines[1].strip().split(' ')
        imgname = filename.split('.')[0] + '.jpg'
        xmlname = filename.split('.')[0] + '.xml'
        img = Image.open(os.path.join(directory, 'images', imgname))
        resizedimg = img.resize((256, 256))
        resizedimg.save(os.path.join(directory, key, 'images', imgname))
        
        node_root = Element('annotation')
        
        node_folder = SubElement(node_root, 'folder')
        node_folder.text = key
        
        node_filename = SubElement(node_root, 'filename')
        node_filename.text = imgname
        
        node_size = SubElement(node_root, 'size')
        node_width = SubElement(node_size, 'width')
        node_width.text = str(resizedimg.width)
        
        node_height = SubElement(node_size, 'height')
        node_height.text = str(resizedimg.height)
        
        node_depth = SubElement(node_size, 'depth')
        node_depth.text = '3'
        
        node_object = SubElement(node_root, 'object')
        node_name = SubElement(node_object, 'name')
        node_name.text = 'plate'
        node_difficult = SubElement(node_object, 'difficult')
        node_difficult.text = '0'
        node_bndbox = SubElement(node_object, 'bndbox')
        node_xmin = SubElement(node_bndbox, 'xmin')
        node_xmin.text = str((int(box[0]) / img.width) * resizedimg.width)
        node_ymin = SubElement(node_bndbox, 'ymin')
        node_ymin.text = str((int(box[1]) / img.width) * resizedimg.width)
        node_xmax = SubElement(node_bndbox, 'xmax')
        node_xmax.text = str((int(box[2]) / img.height) * resizedimg.height)
        node_ymax = SubElement(node_bndbox, 'ymax')
        node_ymax.text = str((int(box[3]) / img.height) * resizedimg.height)
        
        xml = tostring(node_root, pretty_print=True) #Formatted display, the newline of the newline
        dom = parseString(xml)
        print(xml)
        with open(os.path.join(directory, key, 'annotations', xmlname), 'wb') as xmlfile:
          xmlfile.write(xml)

0
b'<annotation>\n  <folder>train</folder>\n  <filename>img00918.jpg</filename>\n  <size>\n    <width>256</width>\n    <height>256</height>\n    <depth>3</depth>\n  </size>\n  <object>\n    <name>plate</name>\n    <difficult>0</difficult>\n    <bndbox>\n      <xmin>80.63608562691131</xmin>\n      <ymin>180.0611620795107</ymin>\n      <xmax>151.23432343234325</xmax>\n      <ymax>216.2904290429043</ymax>\n    </bndbox>\n  </object>\n</annotation>\n'
1
b'<annotation>\n  <folder>train</folder>\n  <filename>img01041.jpg</filename>\n  <size>\n    <width>256</width>\n    <height>256</height>\n    <depth>3</depth>\n  </size>\n  <object>\n    <name>plate</name>\n    <difficult>0</difficult>\n    <bndbox>\n      <xmin>136.74255691768826</xmin>\n      <ymin>192.784588441331</ymin>\n      <xmax>202.56987295825772</xmax>\n      <ymax>223.94192377495463</ymax>\n    </bndbox>\n  </object>\n</annotation>\n'
2
b'<annotation>\n  <folder>train</folder>\n  <filename>img01061.jpg</filename>\n  <size>\n    

In [8]:
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="plates")
trainer.setTrainConfig(object_names_array=["plate"], batch_size=4, num_experiments=10, train_from_pretrained_model="pretrained-yolov3.h5")
trainer.trainModel()

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

Generating anchor boxes for training images and annotation...


/usr/local/lib/python3.6/dist-packages/imageai/Detection/Custom/gen_anchors.py:15: RuntimeWarning: invalid value encountered in double_scalars
  similarity = w*h/(c_w*c_h)


Average IOU for 9 anchors: nan
Anchor Boxes generated.
Detection configuration saved in  plates/json/detection_config.json
Training on: 	['plate']
Training with Batch Size:  4
Number of Experiments:  10
Instructions for updating:
Use `tf.cast` instead.

Training with transfer learning from pretrained Model


/usr/local/lib/python3.6/dist-packages/keras/callbacks/callbacks.py:998: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '







Epoch 1/10
   2/2976 [..............................] - ETA: 36:06:24 - loss: 138.7263 - yolo_layer_1_loss: 26.0808 - yolo_layer_2_loss: 38.1995 - yolo_layer_3_loss: 74.4461

KeyboardInterrupt: ignored

In [ ]:
# from PIL import Image 
# import os

# dataset = []
# directory = '/content/drive/My Drive/PalestinePlateDataSet';
# i = 0

# for filename in os.listdir(directory + '/annotation'):
#   print(filename, i)
#   i += 1
#   if filename.endswith(".txt"): 
#     obj = {}
#     with open(os.path.join(directory, 'annotation', filename), 'r') as f:
#       lines = f.readlines()
#       obj['plate'] = lines[0].strip()
#       obj['box'] = lines[1].strip().split(' ')
#     imgname = filename.split('.')[0] + '.jpg'
#     obj['img'] = Image.open(os.path.join(directory, 'images', imgname))
#     dataset.append(obj)

In [ ]:
###########

In [ ]:
# # keras imports for the dataset and building our neural network
# from keras.datasets import mnist
# from keras.models import Sequential
# from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
# from keras.utils import np_utils

# # to calculate accuracy
# from sklearn.metrics import accuracy_score

# # loading the dataset
# (X_train, y_train), (X_test, y_test) = mnist.load_data()
# print(X_train)
# print(X_train.shape)
# print(y_train)
# print(y_train.shape)

# # building the input vector from the 28x28 pixels
# X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
# X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
# X_train = X_train.astype('float32')
# X_test = X_test.astype('float32')

# # normalizing the data to help with the training
# X_train /= 255
# X_test /= 255

# # one-hot encoding using keras' numpy-related utilities
# n_classes = 10
# print("Shape before one-hot encoding: ", y_train.shape)
# Y_train = np_utils.to_categorical(y_train, n_classes)
# Y_test = np_utils.to_categorical(y_test, n_classes)
# print("Shape after one-hot encoding: ", Y_train.shape)

# # building a linear stack of layers with the sequential model
# model = Sequential()
# # convolutional layer
# model.add(Conv2D(25, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape=(28,28,1)))
# model.add(MaxPool2D(pool_size=(1,1)))
# # flatten output of conv
# model.add(Flatten())
# # hidden layer
# model.add(Dense(100, activation='relu'))
# # output layer
# model.add(Dense(10, activation='softmax'))

# # compiling the sequential model
# model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# # training the model for 10 epochs
# model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data=(X_test, Y_test))

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
(60000, 28, 28)
[5 0 4 ... 5 6 8]
(60000,)
Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)
Epoch 1/10
208/469 [============>.................] - ETA: 17s - loss: 0.5460 - accuracy: 0.8410

KeyboardInterrupt: ignored